SELECT CITY, LEN(CITY) 
FROM ( 
    SELECT CITY, LEN(CITY) AS CITY_LENGTH, 
    ROW_NUMBER() OVER (ORDER BY LEN(CITY) ASC, CITY ASC) AS SHORTEST_RANK, 
    ROW_NUMBER() OVER (ORDER BY LEN(CITY) DESC, CITY ASC) AS LONGEST_RANK 
    FROM STATION ) RANKED 
WHERE SHORTEST_RANK = 1 OR LONGEST_RANK = 1;