SELECT 
 CONVERT(numeric(12,2),ROUND(SUM(LAT_N),2) )
,CONVERT(numeric(12,2),ROUND(SUM(LONG_W),2) )
FROM STATION;

SELECT 
 CONVERT(decimal(12,4),ROUND(SUM(LAT_N),4,1))
FROM STATION
WHERE LAT_N> 38.7880 AND LAT_N < 137.2345;

SELECT 
 CONVERT(decimal(12,4),ROUND(MAX(LAT_N),4,1))
FROM STATION
WHERE  LAT_N < 137.2345;

SELECT CONVERT(decimal(12,4),LONG_W)
FROM STATION
WHERE LAT_N=(
        SELECT 
         MAX(LAT_N)
        FROM STATION
        WHERE  LAT_N < 137.2345
);



SELECT 
 CONVERT(decimal(12,4),ROUND(MIN(LAT_N),4))
FROM STATION
WHERE  LAT_N > 38.7780;


SELECT CONVERT(decimal(12,4),LONG_W)
FROM STATION
WHERE LAT_N=(
        SELECT 
         MIN(LAT_N)
        FROM STATION
        WHERE  LAT_N > 38.7780
);