SELECT 
CONCAT(N, ' ', 
       CASE
       WHEN P IS NULL THEN 'Root' 
       WHEN N IN (SELECT DISTINCT P FROM BST) THEN 'Leaf' 
       ELSE 'Inner' END) AS BST_Classification 
FROM BST ORDER BY N;

SELECT 
CASE 
WHEN P IS NULL THEN CONCAT(N, ' Root') 
WHEN N IN (SELECT DISTINCT P FROM BST) THEN CONCAT(N, ' Inner') 
ELSE CONCAT(N, ' Leaf') 
END FROM BST ORDER BY N;